### ISSUE TITLE
self.config_advisor.get_suggestion()  is running slower and slower，even once every tens of seconds

### ISSUE THREAD

**Issue by jifeiran** [PKU-DAIR/open-box#12]
您好，我启动了多个进程openbox实例，总进程数量是小于cpu核心数量的，每个openbox都是单进程模式Optimizer(....)，max_runs 设置的是500次，运行时发现，在前几十次时速度还是比较快的，但到后面会越来越慢，运行到100-300轮的时候，每次获取参数都要几十秒的时间，请问这是什么原因，怎么解决，多谢？ 
Hello, I have started several OPENBOX instances. The total number of processes is less than the number of CPU cores. Each OPENBOX is a single process mode optimizer (...), max_ Runs is set to 500 times. It is found that the speed is still relatively fast in the first dozens of times, but it will be slower and slower later. When running to 100-300 rounds, it takes tens of seconds to obtain parameters every time. What is the reason and how to solve it? Thank you?

**Comment by jhj0411jhj** [comment]
Thanks for the issue. I guess you are using `GaussianProcess` as surrogate model. The model implemented by `scipy` calls some `numpy` functions, which try to occupy all cpu cores.
I suggest you **put the following code at the beginning of your script**. The code must be executed before you `import numpy` for the first time. Note that importing other libraries may also leads to the importing of numpy.
```python
import os
NUM_THREADS = "1"
os.environ["OMP_NUM_THREADS"] = NUM_THREADS         # export OMP_NUM_THREADS=1
os.environ["OPENBLAS_NUM_THREADS"] = NUM_THREADS    # export OPENBLAS_NUM_THREADS=1
os.environ["MKL_NUM_THREADS"] = NUM_THREADS         # export MKL_NUM_THREADS=1
os.environ["VECLIB_MAXIMUM_THREADS"] = NUM_THREADS  # export VECLIB_MAXIMUM_THREADS=1
os.environ["NUMEXPR_NUM_THREADS"] = NUM_THREADS     # export NUMEXPR_NUM_THREADS=1
```
Then you can import numpy and other libraries.
```python
import numpy as np
````
The code limits cpu threads that `numpy` can use. You can change `NUM_THREADS` according to your machine. And since the computational complexity of Gaussian Process is O(n<sup>3</sup>), it is normal to take a few seconds in later optimization rounds.

**Comment by thomas-young-2013** [comment]
Instead of gp (Gaussian process), we strongly recommend you to set the surrogate_type to "rf (random forest)". Please refer to our doc for details.

**Comment by jifeiran** [comment]
I add the code, the issue is still exist,I use Optimizer ,set max_runs = 1000, other options as same as offical demo. When running 90 to 300 times, the speed becomes slower and slower，even 2 minutes per time ，but after 300 times, the speed quickly return to normal about 3 seconds per time. what `s the problem? How to solve it? Thanks

**Comment by jhj0411jhj** [comment]
According to this paper[1], Gaussian Process(gp) performs better in low-dimensional continuous problems, and probabilistic random forest(prf) performs better in high-dimensional space, or space with categorical/conditional parameters. The computational complexity of PRF is lower than that of GP.

We recommand you to use `prf` if the dimension of space is high, or the space includes many categorical/conditional params, or you want to optimize for more than 200 rounds. Otherwise you can use `gp`.

Ref: 
[1] K. Eggensperger, M. Feurer, F. Hutter, J. Bergstra, J. Snoek, H. Hoos, and K. Leyton-Brown. Towards an empirical foundation for assessing bayesian optimization of hyperparameters. In NIPS workshop on Bayesian Optimization in Theory and Practice, 2013.
