### ISSUE TITLE
Whether can provide some examples of database parameters were optimized ?

### ISSUE THREAD

**Issue by DomineCore** [PKU-DAIR/open-box#53]

**Comment by jhj0411jhj** [comment]
For database tuning examples and parameter settings, please refer to **DBTune** for more details: https://github.com/PKU-DAIR/DBTune

You can either use **DBTune** or **OpenBox** as the optimizer, since they share a similar structure.

Here are some related papers for database tuning:
+ **Facilitating Database Tuning with Hyper-Parameter Optimization: A Comprehensive Experimental Evaluation**[[PDF](https://arxiv.org/abs/2110.12654)] Xinyi Zhang, Zhuo Chang, Yang Li, Hong Wu, Jian Tan, Feifei Li, Bin Cui. The 48th International Conference on Very Large Data Bases . **VLDB 2022, CCF-A**
+ **Towards Dynamic and Safe Configuration Tuning for Cloud Databases**[[PDF](https://arxiv.org/abs/2203.14473)] Xinyi Zhang, Hong Wu, Yang Li, Jian Tan, Feifei Li, Bin Cui. ACM Conference on Management of Data . **SIGMOD 2022, CCF-A**
+ **ResTune: Resource Oriented Tuning Boosted by Meta-Learning for Cloud Databases**[[PDF](https://dl.acm.org/doi/10.1145/3448016.3457291)] Xinyi Zhang, Hong Wu, Zhuo Chang, Shuowei Jin, Jian Tan, Feifei Li, Tieying Zhang, and Bin Cui. ACM Conference on Management of Data . **SIGMOD 2021, CCF-A**
